import type { Exercise, Fundamental } from './figure-drawing'

const lightColor: Exercise[] = [
  {
    id: 'lc-01',
    title: 'Repaint One Movie Frame',
    goal: 'Study how professional lighting and color choices create mood.',
    how: [
      'Pause a film at a visually striking moment.',
      'Block in the major shapes and value structure.',
      'Repaint using the same color palette and lighting logic.',
    ],
    review: 'What color choice did the most emotional work in the frame?',
  },
  {
    id: 'lc-02',
    title: 'Paint One Object in Moonlight',
    goal: 'Practice cool, low-key lighting with limited value range.',
    how: [
      'Choose one simple object.',
      'Imagine it lit only by cool blue moonlight.',
      'Keep your value range narrow — mostly dark with one source of cool light.',
    ],
    review: 'Did the limited light make the object feel more mysterious?',
  },
  {
    id: 'lc-03',
    title: 'Paint One Object in Grayscale',
    goal: 'Strip away color to focus purely on value relationships.',
    how: [
      'Choose one object with interesting form.',
      'Paint it using only black, white, and grays.',
      'Focus entirely on getting the value transitions correct.',
    ],
    review: 'Did removing color make the lighting easier or harder to read?',
  },
  {
    id: 'lc-04',
    title: 'Paint Using Warm Colors Only',
    goal: 'Practice working within a restricted, harmonious palette.',
    how: [
      'Choose one simple subject.',
      'Select only warm colors — reds, oranges, yellows.',
      'Paint the entire piece, using value (not color) to create contrast.',
    ],
    review: 'How did limiting to warm colors affect the mood?',
  },
  {
    id: 'lc-05',
    title: 'Study One Master Painting',
    goal: 'Learn directly from how historical artists solved light and color.',
    how: [
      'Choose one painting from an artist you admire.',
      'Identify their light source and core color palette.',
      'Do a simplified color study recreating their major value and color shapes.',
    ],
    review: 'What is one technique from this artist you want to try again?',
  },
  {
    id: 'lc-06',
    title: 'Three-Value Object Study',
    goal: 'Practice simplifying light into just three clear values.',
    how: [
      'Choose one object with a clear light source.',
      'Identify only three values: light, mid, and dark.',
      'Paint or shade using only those three — no gradients.',
    ],
    review: 'Did the simplified values still read as believable light?',
  },
  {
    id: 'lc-07',
    title: 'Cool Colors Only Study',
    goal: 'Practice the emotional range of a cool, restrained palette.',
    how: [
      'Choose one simple subject.',
      'Select only cool colors — blues, greens, purples.',
      'Paint the piece using value shifts within that cool range.',
    ],
    review: 'What mood did the cool palette create compared to warm?',
  },
  {
    id: 'lc-08',
    title: 'Sunset Lighting Study',
    goal: 'Practice warm, directional, golden-hour light.',
    how: [
      'Choose a simple scene or object.',
      'Imagine strong warm light coming from a low angle.',
      'Exaggerate the warm highlights and cool shadow contrast.',
    ],
    review: 'Did the warm/cool contrast make the light feel believable?',
  },
  {
    id: 'lc-09',
    title: 'Overcast Lighting Study',
    goal: 'Practice soft, diffused light with minimal shadow contrast.',
    how: [
      'Choose a simple object or figure.',
      'Imagine it lit by soft, even overcast daylight.',
      'Use a narrow value range with very soft shadow edges.',
    ],
    review: 'How did soft lighting change the mood compared to direct sun?',
  },
  {
    id: 'lc-10',
    title: 'Candlelight Study',
    goal: 'Practice warm, localized, dramatic lighting.',
    how: [
      'Choose a simple object or face.',
      'Imagine a single candle as the only light source, close to the subject.',
      'Use strong warm highlights that fall off quickly into dark shadow.',
    ],
    review: 'Did the light falloff feel fast enough to read as a small flame?',
  },
  {
    id: 'lc-11',
    title: 'Complementary Color Study',
    goal: 'Practice using opposite colors to create visual energy.',
    how: [
      'Choose one simple subject.',
      'Pick a pair of complementary colors (e.g. orange and blue).',
      'Paint using mostly one color, with the other as accent and shadow.',
    ],
    review: 'Where did the complementary color create the most contrast?',
  },
  {
    id: 'lc-12',
    title: 'Monochrome Color Study',
    goal: 'Practice creating depth and interest using only one hue.',
    how: [
      'Choose one color.',
      'Paint a simple subject using only tints and shades of that single color.',
      'Rely on value shifts, not hue changes, for all the form.',
    ],
    review: 'Did one color feel limiting, or were you able to create enough contrast?',
  },
  {
    id: 'lc-13',
    title: 'Rim Light Study',
    goal: 'Practice a light source positioned behind the subject.',
    how: [
      'Choose a simple object or figure silhouette.',
      'Imagine the light source directly behind it.',
      'Paint the subject mostly in shadow, with a thin bright edge outlining the form.',
    ],
    review: 'Did the rim light help separate the subject from its background?',
  },
  {
    id: 'lc-14',
    title: 'Color Temperature Shift Study',
    goal: 'Practice showing the transition from warm light to cool shadow.',
    how: [
      'Choose one simple object with a clear light source.',
      'Paint the lit side using warm colors.',
      'Paint the shadow side using cool colors, even if subtly.',
    ],
    review: 'Did the warm-to-cool shift make the form feel more three-dimensional?',
  },
  {
    id: 'lc-15',
    title: 'Limited Palette: 4 Colors',
    goal: 'Practice creating a full range of color using minimal pigments.',
    how: [
      'Choose exactly 4 colors (e.g. red, yellow, blue, white).',
      'Paint a simple scene using only mixes of those 4.',
      'Avoid using any other color, even if it feels limiting.',
    ],
    review: 'What surprising colors did you mix from your limited palette?',
  },
  {
    id: 'lc-16',
    title: 'Studio Light Study',
    goal: 'Practice clean, controlled, single-source studio lighting.',
    how: [
      'Choose a simple object.',
      'Imagine one clean light source from a 45-degree angle.',
      'Paint with clear light, mid, and shadow planes — no ambient bounce.',
    ],
    review: 'Did the single clean light source feel easier to control?',
  },
  {
    id: 'lc-17',
    title: 'Bounce Light Study',
    goal: 'Practice the subtle effect of light reflecting off nearby surfaces.',
    how: [
      'Choose a simple object near a colorful surface (e.g. red wall).',
      'Paint the main light source as usual.',
      'Add a subtle tint of the surrounding color into the shadow side.',
    ],
    review: 'Did the bounce light make the shadow feel less flat?',
  },
  {
    id: 'lc-18',
    title: 'Color Mood Board: 3 Moods',
    goal: 'Practice quickly generating different emotional palettes.',
    how: [
      'Choose 3 moods: e.g. calm, tense, joyful.',
      'Paint 3 small color swatches or thumbnails, one per mood.',
      'Use only color and value — no detail.',
    ],
    review: 'Which mood was easiest to express through color alone?',
  },
  {
    id: 'lc-19',
    title: 'Skin Tone Light Study',
    goal: 'Practice the specific challenge of lighting on skin.',
    how: [
      'Find a simple portrait or hand reference.',
      'Identify the light, mid, and shadow values on the skin.',
      'Paint focusing on subtle warm and cool shifts within the skin tone.',
    ],
    review: 'Did you notice any cool tones within the warm skin shadows?',
  },
  {
    id: 'lc-20',
    title: 'Night Scene Study',
    goal: 'Practice a low-key scene with multiple small light sources.',
    how: [
      'Imagine a night scene with 2-3 small lights (windows, lamps, signs).',
      'Keep the overall value dark.',
      'Paint each light source with a glow that fades into the darkness.',
    ],
    review: 'Did the small lights feel like they were actually glowing?',
  },
  {
    id: 'lc-21',
    title: 'Color Harmony: Analogous Palette',
    goal: 'Practice a palette using colors that sit next to each other on the wheel.',
    how: [
      'Choose 3 colors that are next to each other (e.g. yellow, orange, red).',
      'Paint a simple subject using only this analogous range.',
      'Use value shifts to create contrast within the harmony.',
    ],
    review: 'Did the analogous palette feel naturally harmonious?',
  },
  {
    id: 'lc-22',
    title: 'High-Key Lighting Study',
    goal: 'Practice a bright scene with minimal shadow contrast.',
    how: [
      'Choose a simple subject.',
      'Paint it almost entirely in light and mid values.',
      'Use just a touch of shadow for form, keeping the overall feel bright and airy.',
    ],
    review: 'What mood did the bright, low-contrast lighting create?',
  },
  {
    id: 'lc-23',
    title: 'Low-Key Lighting Study',
    goal: 'Practice a dark, dramatic scene with selective lighting.',
    how: [
      'Choose a simple subject.',
      'Paint it almost entirely in dark values.',
      'Use one small, bright highlight to draw the eye.',
    ],
    review: 'Did the single highlight feel powerful against the dark values?',
  },
  {
    id: 'lc-24',
    title: 'Color Study from a Photo',
    goal: 'Practice extracting and recreating a real-world color palette.',
    how: [
      'Choose a photo with interesting lighting.',
      'Pick out the 4-5 dominant colors you see.',
      'Paint a simplified version using only those extracted colors.',
    ],
    review: 'Were the dominant colors what you initially expected?',
  },
  {
    id: 'lc-25',
    title: 'Underwater Light Study',
    goal: 'Practice unusual, filtered, color-shifted lighting.',
    how: [
      'Imagine a simple object underwater.',
      'Shift the overall palette toward blue-green.',
      'Soften edges slightly to suggest light diffusing through water.',
    ],
    review: 'How did the color shift change the mood of the object?',
  },
  {
    id: 'lc-26',
    title: 'Fire Light Study',
    goal: 'Practice intense, flickering, warm light on a nearby subject.',
    how: [
      'Imagine a simple object lit by a nearby fire.',
      'Use strong warm oranges and yellows on the lit side.',
      'Add deep, slightly red-tinted shadows on the opposite side.',
    ],
    review: 'Did the warm light feel intense enough to suggest fire?',
  },
  {
    id: 'lc-27',
    title: 'Color Grading Exercise',
    goal: 'Practice shifting an existing piece\'s mood using an overall color tint.',
    how: [
      'Choose one of your earlier color studies.',
      'Duplicate or redo it with a single warm-toned overlay.',
      'Redo it again with a single cool-toned overlay.',
    ],
    review: 'Which version felt more emotionally effective?',
  },
  {
    id: 'lc-28',
    title: 'Reflected Color Study',
    goal: 'Practice how colorful surroundings affect a neutral object.',
    how: [
      'Imagine a white or gray object surrounded by colorful objects.',
      'Paint the object\'s shadow side picking up hints of the surrounding colors.',
      'Keep the lit side closer to neutral.',
    ],
    review: 'Did the reflected color make the object feel embedded in its scene?',
  },
  {
    id: 'lc-29',
    title: 'Two-Light Color Study',
    goal: 'Practice mixing warm and cool light sources in one scene.',
    how: [
      'Choose a simple object.',
      'Light one side with a warm source and the other with a cool source.',
      'Paint where the two lights meet and blend.',
    ],
    review: 'Did the meeting point of the two lights feel natural?',
  },
  {
    id: 'lc-30',
    title: 'Seasonal Light Study',
    goal: 'Practice how light and color shift across seasons.',
    how: [
      'Choose one simple scene or object.',
      'Paint it once in cool, blue-toned winter light.',
      'Paint it again in warm, golden autumn light.',
    ],
    review: 'Which seasonal palette felt more natural to paint?',
  },
  {
    id: 'lc-31',
    title: 'Color Speed Study',
    goal: 'Practice quick, intuitive color decisions under time pressure.',
    how: [
      'Set a timer for 10 minutes.',
      'Choose any simple subject.',
      'Paint it start to finish before the timer runs out — no overthinking.',
    ],
    review: 'Did working fast change your color choices for better or worse?',
  },
  {
    id: 'lc-32',
    title: 'Light Logic Speed Round',
    goal: 'Test recall of lighting principles under time pressure.',
    how: [
      'Set a timer for 12 minutes.',
      'Light one sphere, one cube, and one cylinder — same light source, from memory.',
      'No references — apply what you\'ve already practiced.',
    ],
    review: 'Did your light direction stay consistent across all three forms?',
  },
]

export const LIGHT_COLOR: Fundamental = {
  id: 'light-color',
  name: 'Light & Color',
  tagline: 'Mood, palette, and the logic of how light behaves.',
  exercises: lightColor,
}
